# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ducbui/Documents/Coding/codebrew

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ducbui/Documents/Coding/codebrew

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ducbui/Documents/Coding/codebrew/CMakeFiles /Users/ducbui/Documents/Coding/codebrew//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ducbui/Documents/Coding/codebrew/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named codebrew

# Build rule for target.
codebrew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codebrew
.PHONY : codebrew

# fast build rule for target.
codebrew/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/build
.PHONY : codebrew/fast

lib/tigr.o: lib/tigr.c.o
.PHONY : lib/tigr.o

# target to build an object file
lib/tigr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/lib/tigr.c.o
.PHONY : lib/tigr.c.o

lib/tigr.i: lib/tigr.c.i
.PHONY : lib/tigr.i

# target to preprocess a source file
lib/tigr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/lib/tigr.c.i
.PHONY : lib/tigr.c.i

lib/tigr.s: lib/tigr.c.s
.PHONY : lib/tigr.s

# target to generate assembly for a file
lib/tigr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/lib/tigr.c.s
.PHONY : lib/tigr.c.s

src/cube.o: src/cube.c.o
.PHONY : src/cube.o

# target to build an object file
src/cube.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/cube.c.o
.PHONY : src/cube.c.o

src/cube.i: src/cube.c.i
.PHONY : src/cube.i

# target to preprocess a source file
src/cube.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/cube.c.i
.PHONY : src/cube.c.i

src/cube.s: src/cube.c.s
.PHONY : src/cube.s

# target to generate assembly for a file
src/cube.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/cube.c.s
.PHONY : src/cube.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/main.c.s
.PHONY : src/main.c.s

src/ray.o: src/ray.c.o
.PHONY : src/ray.o

# target to build an object file
src/ray.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/ray.c.o
.PHONY : src/ray.c.o

src/ray.i: src/ray.c.i
.PHONY : src/ray.i

# target to preprocess a source file
src/ray.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/ray.c.i
.PHONY : src/ray.c.i

src/ray.s: src/ray.c.s
.PHONY : src/ray.s

# target to generate assembly for a file
src/ray.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/ray.c.s
.PHONY : src/ray.c.s

src/triangles.o: src/triangles.c.o
.PHONY : src/triangles.o

# target to build an object file
src/triangles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/triangles.c.o
.PHONY : src/triangles.c.o

src/triangles.i: src/triangles.c.i
.PHONY : src/triangles.i

# target to preprocess a source file
src/triangles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/triangles.c.i
.PHONY : src/triangles.c.i

src/triangles.s: src/triangles.c.s
.PHONY : src/triangles.s

# target to generate assembly for a file
src/triangles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codebrew.dir/build.make CMakeFiles/codebrew.dir/src/triangles.c.s
.PHONY : src/triangles.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... codebrew"
	@echo "... lib/tigr.o"
	@echo "... lib/tigr.i"
	@echo "... lib/tigr.s"
	@echo "... src/cube.o"
	@echo "... src/cube.i"
	@echo "... src/cube.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ray.o"
	@echo "... src/ray.i"
	@echo "... src/ray.s"
	@echo "... src/triangles.o"
	@echo "... src/triangles.i"
	@echo "... src/triangles.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

